#!/bin/bash
# start (without the .sh)
# bootstraping script
# Rogelio Zárate 
# i.am@rogeliozarate.com
# 2012-04-09T22:59:41

if [ $1 ]
then
  BASE_DIR=~/code/
  DIR=$BASE_DIR$1
  APP_NAME=$1
  if [ -d "$DIR" ]; then
    # Control will enter here if $DIRECTORY exists
    echo "Directory ${DIR} exist. Choose a different name"
    exit
  else
    read -p "Are you sure you want to create the app structure? [yY]" -n 1 -r
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
	    echo
	    echo "Creating structure"
	    mkdir $DIR
	    cd $DIR
	    git init . 
	    rvm use default@$APP_NAME --create --rvmrc
	    touch Gemfile
	    touch .gitignore
	    touch readme.md
	    rvm reload
	    echo "Script finished at $(date)"
	    echo "Future is yours"
	 else
		echo
		echo "Second thougts eh? at $(date)"
		exit
	fi
  fi
else  
  echo "App name is null, leaving the script"
  exit
fi